### ISSUE TITLE
Add a visual to display the state of sword block/How much sword is blocking.

### ISSUE THREAD

**Issue by L1ghtman2k** [Dinorush/LTSRebalance#2]
I think a basic counter/visual display could do for starters, just so ronin can better assess the situation, and get a feel for how sword block discharges/recharges

**Comment by Dinorush** [comment]
The user can see block charge on the ammo bar, though enemies can't really discern it. I'll look into perhaps tying block animations to it (and remove the on-hit block anim changes).

**Comment by L1ghtman2k** [comment]
Ah, I didn't notice it I think. this can be closed
