### ISSUE TITLE
Permission to translate into chinese plz？

### ISSUE THREAD

**Issue by rogo921** [Dinorush/LTSRebalance#6]
Hello dinorush！When I see your mod in thunderstore I immediately share it to my friends and test in my server.In chinese ttf2 northstar community, the total player number is 500+ and active player number is 200~300，and we have a 80+ player group in social media platform which focus on hardcore ttdm combat gameplay. We all agree that your mod did really great work！Adding a lot of fresh and interesting contene while keeping the gameplay balanced.
  Considering your mod changed so many content，We think giving a certain translate to your mod content and mod document is necessary.And after thay maybe we can give the community feedback and help to debug. Even oneday give a balance edition to ttdm mode.
  Thanks you and your work！

**Comment by Dinorush** [comment]
Absolutely feel free to. The mod is already built to support localizations. It in fact used to have German, but it was never updated by those who did it so I had to remove it.
